sudo: false

language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test

before_install:
    - pip install --user cpp-coveralls

compiler:  
    - gcc

before_script:  
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=On

script: 
    - make
    - ctest -V

after_success:
    - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" -E ".*gtest.*"
