version: 2.1

jobs:
  my-compile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Install libs"
          command: "sudo apt-get update && sudo apt-get -qq -y install libev-dev librrd-dev libsystemd-dev libgtest-dev"
      - run:
          name: "build"
          command: |
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=On
            make -j$(nproc)
      - run:
          name: "Test"
          command: |
            make check test
      - store_test_results:
          path: build/out.xml
#      - run:
#          name: "Install cpp-coveralls"
#          command: "pip install --user cpp-coveralls"

workflows:
  compile-workflow:
    jobs:
      - my-compile
