version: 2.1

jobs:
  my-compile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Install libs"
          command: "sudo apt-get -qq -y install libev-dev librrd-dev libsystemd-dev libgtest-dev"
      - run:
          name: "Build"
          command: "mkdir build && cmake -S . -B build"
      - run:
          name: "Test"
          command: "ctest --test-dir build --output-junit out.xml"
      - store_test_results:
          path: build/out.xml
#      - run:
#          name: "Install cpp-coveralls"
#          command: "pip install --user cpp-coveralls"

workflows:
  compile-workflow:
    jobs:
      - my-compile
